<?php

namespace AsseticBundleTest;

use PHPUnit\Framework\TestCase;
use Prophecy\PhpUnit\ProphecyTrait;
use Laminas\ServiceManager;
use Assetic;
use Fabiang\AsseticBundle;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-17 at 11:53:23.
 */
class FilterManagerTest extends TestCase
{

    use ProphecyTrait;

    /**
     * @var Fabiang\AsseticBundle\FilterManager
     */
    protected $object;

    /**
     * @var ServiceManager\ServiceManager
     */
    protected $service;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->service = new ServiceManager\ServiceManager();
        $this->object  = new AsseticBundle\FilterManager($this->service);
    }

    /**
     * @dataProvider getAliasHasFalseProvider
     */
    public function testHasFalse($alias)
    {
        $this->assertFalse($this->object->has($alias));
    }

    public function getAliasHasFalseProvider()
    {
        return [
            'simple'       => [
                '$alias' => 'simpleName',
            ],
            'invalid name' => [
                '$alias' => '@_simpleName',
            ],
        ];
    }

    /**
     * @dataProvider getAliasGetExceptionProvider
     */
    public function testGetException($alias)
    {
        $this->expectException(AsseticBundle\Exception\InvalidArgumentException::class);
        $this->object->get($alias);
    }

    public function getAliasGetExceptionProvider()
    {
        return [
            'no existing'  => [
                '$alias' => 'simpleName',
            ],
            'invalid name' => [
                '$alias' => '@_simpleName',
            ],
        ];
    }

    /**
     * @dataProvider getAliasGetExceptionInstanceProvider
     */
    public function testGetExceptionInstance($alias, $object)
    {
        $this->expectException(AsseticBundle\Exception\InvalidArgumentException::class);
        $this->service->setService($alias, $object);
        $this->object->get($alias);
    }

    public function getAliasGetExceptionInstanceProvider()
    {
        return [
            'simple' => [
                '$alias'  => 'simpleName',
                '$object' => new \stdClass(),
            ],
        ];
    }

    /**
     * @dataProvider getAliasGetValidProvider
     */
    public function testGetValid($alias, $object)
    {
        $this->assertInstanceOf(\Assetic\Contracts\Filter\FilterInterface::class, $object);
        $this->service->setService($alias, $object);
        $result = $this->object->get($alias);
        $this->assertInstanceOf('Assetic\Filter\FilterInterface', $result);
        $this->assertSame($result, $object);
    }

    public function getAliasGetValidProvider()
    {
        return [
            'simple' => [
                '$alias'  => 'simpleName',
                '$object' => $this->prophesize(\Assetic\Contracts\Filter\FilterInterface::class)->reveal(),
            ],
        ];
    }

}
